In [1]:
import numpy as np
import sys

class Gauss:

    #Inisiasi Matrix
    def start(self):  #self variabel yg mewakili turunan dari objek itu sendiri
        self.n = int(input("Enter the number of unknowns: ")) #memasukkan baris
        self.A = np.zeros((self.n,self.n+1)) #pembuatan matriks #np zeros adalah fungsi mengembalikan larik baru dengan bentuk dan tipe tertentu, dengan nol #pembuatan kolom=baris+ 1
        self.R = np.zeros((self.n,self.n+1)) #Matriks perkalian untuk kolom
        self.x = np.zeros(self.n) #Solution array-nya

        print("Masukkan augmented matrix coefficients: ")
        for i in range(self.n): #pengulangan baris
            for j in range(self.n+1): #pengulangan kolom
                self.A[i][j] = input("matrix["+ str(i) +"]["+ str(j) +"] = ")
    
    #Gauss Elimination
    def gaussProg(self):
        print(f"\nGauss Elimination\ninisiasi matrix:\n {self.A}")
        for i in range(self.n-1): #loop kolom
            if self.A[i][i] == 0:
                sys.exit("Dibagi dengan 0(proses tidak dilanjutkan...)") #kondisi system ketika membagi dengan 0
            print(f"\nTransformation {i+1}: ")

            #Menghitung perkalian untuk kolom saat ini
            for j in range(i+1, self.n):
                self.R[j][i] = self.A[j][i] / self.A[i][i]
                print(f"baris{j+1} = row{j+1} - {self.R[j][i]} * baris{i+1}")

            #Terapkan transformasi ke submatrix yang tersisa
            for k in range(self.n+1):
                for j in range(self.n):
                    self.A[j][k] = self.A[j][k] - self.R[j][i] * self.A[i][k]

            print(f"Hasil:\n {self.A}")
    
    #Substitusi kembali
    def Subs(self):
        self.x[self.n-1] = self.A[self.n-1][self.n] / self.A[self.n-1][self.n-1]
        for i in range(self.n-2,-1,-1):
            self.x[i] = self.A[i][self.n]
            for j in range(i+1, self.n):
                self.x[i] = self.x[i] - self.A[i][j] * self.x[j]
            self.x[i] = self.x[i] / self.A[i][i]

    #Tampilan/pemecahan
    def display(self):
        print("\nSolusi: ")
        for i in range(self.n):
            print("x%d = %0.2f" %(i+1, self.x[i]))

g = Gauss() #manggil class
g.start() #mulai jalankan class
choice = input("\nKetik Y untuk mengetahui hasilnya: ")
if choice == 'Y':
    g.gaussProg() #jalankan fungsi gauss
else:
    print("Anda menghentikan program")
    quit()
g.Subs() #jalankan fungsi subtitusi kembali
g.display() #jalankan fungsi tampilan

Enter the number of unknowns: 4
Masukkan augmented matrix coefficients: 
matrix[0][0] = 1
matrix[0][1] = -1
matrix[0][2] = 1
matrix[0][3] = -2
matrix[0][4] = 8
matrix[1][0] = 2
matrix[1][1] = -1
matrix[1][2] = 2
matrix[1][3] = -1
matrix[1][4] = 5
matrix[2][0] = -1
matrix[2][1] = 1
matrix[2][2] = 2
matrix[2][3] = -1
matrix[2][4] = 4
matrix[3][0] = 1
matrix[3][1] = 2
matrix[3][2] = 4
matrix[3][3] = 1
matrix[3][4] = 5

Ketik Y untuk mengetahui hasilnya: Y

Gauss Elimination
inisiasi matrix:
 [[ 1. -1.  1. -2.  8.]
 [ 2. -1.  2. -1.  5.]
 [-1.  1.  2. -1.  4.]
 [ 1.  2.  4.  1.  5.]]

Transformation 1: 
baris2 = row2 - 2.0 * baris1
baris3 = row3 - -1.0 * baris1
baris4 = row4 - 1.0 * baris1
Hasil:
 [[  1.  -1.   1.  -2.   8.]
 [  0.   1.   0.   3. -11.]
 [  0.   0.   3.  -3.  12.]
 [  0.   3.   3.   3.  -3.]]

Transformation 2: 
baris3 = row3 - 0.0 * baris2
baris4 = row4 - 3.0 * baris2
Hasil:
 [[  1.  -1.   1.  -2.   8.]
 [  0.   1.   0.   3. -11.]
 [  0.   0.   3.  -3.  12.]
 [  0.   0.   